### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by Renaud-4242** [CCB-SB/plsdb#30] opened 2024-11-11 10:46 UTC
Thank you for your PLSDB that seems great!

To start with, I simply tried to run the various search strategies from https://ccb-microbe.cs.uni-saarland.de/plsdb2025/search. 
However, using the 4 samples provided, I could not run any of them. Each time I got the "Server Error (500)" (using Firefox or Brave browsers).
I looked up the Mash manual at https://mash.readthedocs.io/en/latest/ but could not find my way through.
Any hint about how/what I should do please?
Thank you in advance
Regards
R

**Comment by G-Molano-LA** [comment] 2024-11-11 16:07
Hi @Renaud-4242,

The issue is now fixed. Our apologies for the inconveniences. In the next few weeks, the old plsdb webpage will be replaced with the new one that you pointed out, which will avoid this kind of errors.

Bests,

Alejandra

**Closed as completed by G-Molano-LA** 2024-11-11 16:07 UTC
Labels: bug

**Comment by Renaud-4242** [comment] 2024-11-12 15:08
Many thanks Alejandra, It seems to work indeed
Mash screen result:
- *Job Status* Finished 169 hits
- ...
[image: image.png]

Best regards
Renaud


Le lun. 11 nov. 2024 à 17:07, G-Molano-LA ***@***.***> a
écrit :
